export {default as Home} from "./Home"
export {default as Gallery} from "./Gallery"
export {default as Projects} from "./Projects"
export {default as Certifications} from "./Certifications"
export {default as Contacts} from "./Contacts"
